//===----------------------------------------------------------------------===//
// Gawee Dialect C++ Header
//===----------------------------------------------------------------------===//
//
// LEARNING: This header includes the auto-generated code from TableGen.
//
// The .inc files are generated by mlir-tblgen:
//   mlir-tblgen --gen-dialect-decls GaweeDialect.td -o GaweeDialect.h.inc
//   mlir-tblgen --gen-op-decls GaweeOps.td -o GaweeOps.h.inc
//
// You don't write these .inc files - they're auto-generated!
//
//===----------------------------------------------------------------------===//

#ifndef GAWEE_DIALECT_H
#define GAWEE_DIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/Builders.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

//===----------------------------------------------------------------------===//
// Include TableGen-generated dialect declaration
//===----------------------------------------------------------------------===//
//
// LEARNING: This include brings in the GaweeDialect class declaration
// It defines: class GaweeDialect : public mlir::Dialect { ... }
//

#include "Gawee/GaweeDialect.h.inc"

//===----------------------------------------------------------------------===//
// Include TableGen-generated operation declarations
//===----------------------------------------------------------------------===//
//
// LEARNING: This brings in all op classes: ConvOp, ReluOp, etc.
// Each op becomes a C++ class with builders, accessors, verifiers.
//

#define GET_OP_CLASSES
#include "Gawee/GaweeOps.h.inc"

#endif // GAWEE_DIALECT_H
